package mnj.mfg.model.client;

import mnj.mfg.model.common.MainAM;

import oracle.jbo.Row;
import oracle.jbo.client.remote.ApplicationModuleImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 12:39:17 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class MainAMClient extends ApplicationModuleImpl implements MainAM {
    /**
     * This is the default constructor (do not remove).
     */
    public MainAMClient() {
    }


    public void FillRollLines() {
        Object _ret = this.riInvokeExportedMethod(this,"FillRollLines",null,null);
        return;
    }

    public void setRollwhereClause() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClause",null,null);
        return;
    }

    public void FillRollLines1() {
        Object _ret = this.riInvokeExportedMethod(this,"FillRollLines1",null,null);
        return;
    }

    public void setRollwhereClause1() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClause1",null,null);
        return;
    }

    public void popSizeAll(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"popSizeAll",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public void popSizeAll1(Row poprow) {
        Object _ret =
            this.riInvokeExportedMethod(this,"popSizeAll1",new String [] {"oracle.jbo.Row"},new Object[] {poprow});
        return;
    }

    public void selectAllLines(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void selectAllLines1(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines1",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }

    public void setRollwhereClauseBPO() {
        Object _ret =
            this.riInvokeExportedMethod(this,"setRollwhereClauseBPO",null,null);
        return;
    }

    public void FillRollLinesBPO() {
        Object _ret =
            this.riInvokeExportedMethod(this,"FillRollLinesBPO",null,null);
        return;
    }

    public void setSessionValues(String orgId, String userId, String respId,
                                 String respAppl) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSessionValues",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {orgId, userId, respId, respAppl});
        return;
    }

    public void setSizeWhereClause(String bpo, String stn, String color,
                                   String challan_no) {
        Object _ret =
            this.riInvokeExportedMethod(this,"setSizeWhereClause",new String [] {"java.lang.String","java.lang.String","java.lang.String","java.lang.String"},new Object[] {bpo, stn, color, challan_no});
        return;
    }

    public void receiveSizeQtyValueChangeListener(String Quantity) {
        Object _ret =
            this.riInvokeExportedMethod(this,"receiveSizeQtyValueChangeListener",new String [] {"java.lang.String"},new Object[] {Quantity});
        return;
    }

    public void pageLoadEvent() {
        Object _ret = this.riInvokeExportedMethod(this,"pageLoadEvent",null,null);
        return;
    }

    public void selectAllLines0(String flag) {
        Object _ret =
            this.riInvokeExportedMethod(this,"selectAllLines0",new String [] {"java.lang.String"},new Object[] {flag});
        return;
    }
}
