package mnj.mfg.model.views;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 15 15:32:54 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class LineHeaderEOViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public LineHeaderEOViewImpl() {
    }
}
