package mnj.mfg.model.lov;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 12:50:35 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class RevBPOVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public RevBPOVOImpl() {
    }

    /**
     * Returns the bind variable value for header_Id.
     * @return bind variable value for header_Id
     */
    public String getheader_Id() {
        return (String)getNamedWhereClauseParam("header_Id");
    }

    /**
     * Sets <code>value</code> for bind variable header_Id.
     * @param value value to bind as header_Id
     */
    public void setheader_Id(String value) {
        setNamedWhereClauseParam("header_Id", value);
    }
}
