package mnj.mfg.model.lov;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.ViewRowImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed May 04 14:34:24 PKT 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class similarPopSizeVORowImpl extends ViewRowImpl {
    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        Attribute1 {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getAttribute1();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setAttribute1((String)value);
            }
        }
        ,
        SizeInseam {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getSizeInseam();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setSizeInseam((String)value);
            }
        }
        ,
        Quantity {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getQuantity();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setQuantity((Number)value);
            }
        }
        ,
        HeaderId {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getHeaderId();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setHeaderId((Number)value);
            }
        }
        ,
        LineId {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getLineId();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setLineId((Number)value);
            }
        }
        ,
        Stn {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getStn();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setStn((String)value);
            }
        }
        ,
        Color1 {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getColor1();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setColor1((String)value);
            }
        }
        ,
        Stn1 {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getStn1();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setStn1((String)value);
            }
        }
        ,
        Bpo1 {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getBpo1();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setBpo1((String)value);
            }
        }
        ,
        Buyer {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getBuyer();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setBuyer((String)value);
            }
        }
        ,
        Style {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getStyle();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setStyle((String)value);
            }
        }
        ,
        Season {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getSeason();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setSeason((String)value);
            }
        }
        ,
        IssuanceChallanNo {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getIssuanceChallanNo();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setIssuanceChallanNo((String)value);
            }
        }
        ,
        SFLAG {
            public Object get(similarPopSizeVORowImpl obj) {
                return obj.getSFLAG();
            }

            public void put(similarPopSizeVORowImpl obj, Object value) {
                obj.setSFLAG((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(similarPopSizeVORowImpl object);

        public abstract void put(similarPopSizeVORowImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ATTRIBUTE1 = AttributesEnum.Attribute1.index();
    public static final int SIZEINSEAM = AttributesEnum.SizeInseam.index();
    public static final int QUANTITY = AttributesEnum.Quantity.index();
    public static final int HEADERID = AttributesEnum.HeaderId.index();
    public static final int LINEID = AttributesEnum.LineId.index();
    public static final int STN = AttributesEnum.Stn.index();
    public static final int COLOR1 = AttributesEnum.Color1.index();
    public static final int STN1 = AttributesEnum.Stn1.index();
    public static final int BPO1 = AttributesEnum.Bpo1.index();
    public static final int BUYER = AttributesEnum.Buyer.index();
    public static final int STYLE = AttributesEnum.Style.index();
    public static final int SEASON = AttributesEnum.Season.index();
    public static final int ISSUANCECHALLANNO = AttributesEnum.IssuanceChallanNo.index();
    public static final int SFLAG = AttributesEnum.SFLAG.index();

    /**
     * This is the default constructor (do not remove).
     */
    public similarPopSizeVORowImpl() {
    }

    /**
     * Gets the attribute value for the calculated attribute Attribute1.
     * @return the Attribute1
     */
    public String getAttribute1() {
        return (String) getAttributeInternal(ATTRIBUTE1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Attribute1.
     * @param value value to set the  Attribute1
     */
    public void setAttribute1(String value) {
        setAttributeInternal(ATTRIBUTE1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SizeInseam.
     * @return the SizeInseam
     */
    public String getSizeInseam() {
        return (String) getAttributeInternal(SIZEINSEAM);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SizeInseam.
     * @param value value to set the  SizeInseam
     */
    public void setSizeInseam(String value) {
        setAttributeInternal(SIZEINSEAM, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Quantity.
     * @return the Quantity
     */
    public Number getQuantity() {
        return (Number) getAttributeInternal(QUANTITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Quantity.
     * @param value value to set the  Quantity
     */
    public void setQuantity(Number value) {
        setAttributeInternal(QUANTITY, value);
    }

    /**
     * Gets the attribute value for the calculated attribute HeaderId.
     * @return the HeaderId
     */
    public Number getHeaderId() {
        return (Number) getAttributeInternal(HEADERID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute HeaderId.
     * @param value value to set the  HeaderId
     */
    public void setHeaderId(Number value) {
        setAttributeInternal(HEADERID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute LineId.
     * @return the LineId
     */
    public Number getLineId() {
        return (Number) getAttributeInternal(LINEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute LineId.
     * @param value value to set the  LineId
     */
    public void setLineId(Number value) {
        setAttributeInternal(LINEID, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Stn.
     * @return the Stn
     */
    public String getStn() {
        return (String) getAttributeInternal(STN);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Stn.
     * @param value value to set the  Stn
     */
    public void setStn(String value) {
        setAttributeInternal(STN, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Color1.
     * @return the Color1
     */
    public String getColor1() {
        return (String) getAttributeInternal(COLOR1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Color1.
     * @param value value to set the  Color1
     */
    public void setColor1(String value) {
        setAttributeInternal(COLOR1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Stn1.
     * @return the Stn1
     */
    public String getStn1() {
        return (String) getAttributeInternal(STN1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Stn1.
     * @param value value to set the  Stn1
     */
    public void setStn1(String value) {
        setAttributeInternal(STN1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Bpo1.
     * @return the Bpo1
     */
    public String getBpo1() {
        return (String) getAttributeInternal(BPO1);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Bpo1.
     * @param value value to set the  Bpo1
     */
    public void setBpo1(String value) {
        setAttributeInternal(BPO1, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Buyer.
     * @return the Buyer
     */
    public String getBuyer() {
        return (String) getAttributeInternal(BUYER);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Buyer.
     * @param value value to set the  Buyer
     */
    public void setBuyer(String value) {
        setAttributeInternal(BUYER, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Style.
     * @return the Style
     */
    public String getStyle() {
        return (String) getAttributeInternal(STYLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Style.
     * @param value value to set the  Style
     */
    public void setStyle(String value) {
        setAttributeInternal(STYLE, value);
    }

    /**
     * Gets the attribute value for the calculated attribute Season.
     * @return the Season
     */
    public String getSeason() {
        return (String) getAttributeInternal(SEASON);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute Season.
     * @param value value to set the  Season
     */
    public void setSeason(String value) {
        setAttributeInternal(SEASON, value);
    }

    /**
     * Gets the attribute value for the calculated attribute IssuanceChallanNo.
     * @return the IssuanceChallanNo
     */
    public String getIssuanceChallanNo() {
        return (String) getAttributeInternal(ISSUANCECHALLANNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute IssuanceChallanNo.
     * @param value value to set the  IssuanceChallanNo
     */
    public void setIssuanceChallanNo(String value) {
        setAttributeInternal(ISSUANCECHALLANNO, value);
    }

    /**
     * Gets the attribute value for the calculated attribute SFLAG.
     * @return the SFLAG
     */
    public String getSFLAG() {
        return (String) getAttributeInternal(SFLAG);
    }

    /**
     * Sets <code>value</code> as the attribute value for the calculated attribute SFLAG.
     * @param value value to set the  SFLAG
     */
    public void setSFLAG(String value) {
        setAttributeInternal(SFLAG, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }
}
